### ISSUE TITLE
Latest Autofac.MEF NuGet package references look wrong

### ISSUE THREAD

**Issue by bencyoung** [autofac/Autofac.Mef#10]
The NuGet package says: Autofac (>= 3.3.1 && < 5.0.0)
but then the assembly itself has a strong name on a different version: Autofac, Version=3.3.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da
 so I get:
System.IO.FileLoadException: Could not load file or assembly 'Autofac, Version=3.3.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

if I deploy the latest packages of both (which NuGet allows just fine)

The best solution is not to include the version in the strong name, but releasing an updated MEF NuGet package would work too?

**Comment by tillig** [comment]
In the pre-4.x days we did a slow-rev of the version number, so any minor changes (0.0.1 version change) did not change the strong name. With 4.x we match the semantic version and strong name version exactly, just like the MS framework assemblies.

The NuGet package version constraints refer to other NuGet versions, not assembly strong name versions. I think that's where your mismatch is coming from.

The problem you describe looks like it could be solved with an assembly binding redirect. Usually NuGet puts these in place for you. If it's not happening, you may need to do that yourself. [MSDN has plenty of docs on that.](https://msdn.microsoft.com/en-us/library/7wd6ex19(v=vs.110).aspx)

We don't release a new set of downstream packages every time a new core Autofac is released because that would require a lot of upgrades that aren't necessary.

If you can't get this fixed with a binding redirect, please provide a complete (but minimal) repro so we can see what's up.

**Comment by bencyoung** [comment]
Unfortunately that doesn't work for us. We don't have control of the final application exe and there are other failure cases too. For example I've added the redirect to our project that references Autofac, but VSTest doesn't use it, and we have no access to change any part of this stack trace.

In our applications we've taken to keeping the AssemblyVersion fixed for all time, and just ref the AssemblyFileVersion and AssemblyInformationalVersion instead

>	mscorlib.dll!System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(System.Reflection.AssemblyName assemblyRef, System.Security.Policy.Evidence assemblySecurity, System.Reflection.RuntimeAssembly reqAssembly, ref System.Threading.StackCrawlMark stackMark, System.IntPtr pPrivHostBinder, bool throwOnFileNotFound, bool forIntrospection, bool suppressSecurityChecks)	Unknown
 	mscorlib.dll!System.Reflection.RuntimeAssembly.InternalLoad(string assemblyString, System.Security.Policy.Evidence assemblySecurity, ref System.Threading.StackCrawlMark stackMark, System.IntPtr pPrivHostBinder, bool forIntrospection)	Unknown
 	mscorlib.dll!System.Reflection.RuntimeAssembly.InternalLoad(string assemblyString, System.Security.Policy.Evidence assemblySecurity, ref System.Threading.StackCrawlMark stackMark, bool forIntrospection)	Unknown
 	mscorlib.dll!System.Reflection.Assembly.ReflectionOnlyLoad(string assemblyString)	Unknown
 	Microsoft.VisualStudio.QualityTools.Common.dll!Microsoft.VisualStudio.TestTools.Utility.AssemblyLoadWorker.GetDependentAssembliesInternal(string assemblyString)	Unknown
 	Microsoft.VisualStudio.QualityTools.Common.dll!Microsoft.VisualStudio.TestTools.Utility.AssemblyLoadWorker.ProcessChildren(System.Reflection.Assembly assembly)	Unknown
 	Microsoft.VisualStudio.QualityTools.Common.dll!Microsoft.VisualStudio.TestTools.Utility.AssemblyLoadWorker.GetDependentAssembliesInternal(string assemblyString)	Unknown
 	Microsoft.VisualStudio.QualityTools.Common.dll!Microsoft.VisualStudio.TestTools.Utility.AssemblyLoadWorker.ProcessChildren(System.Reflection.Assembly assembly)	Unknown
 	Microsoft.VisualStudio.QualityTools.Common.dll!Microsoft.VisualStudio.TestTools.Utility.AssemblyLoadWorker.GetDependentAssembliesInternal(string assemblyString)	Unknown
 	Microsoft.VisualStudio.QualityTools.Common.dll!Microsoft.VisualStudio.TestTools.Utility.AssemblyLoadWorker.ProcessChildren(System.Reflection.Assembly assembly)	Unknown
 	Microsoft.VisualStudio.QualityTools.Common.dll!Microsoft.VisualStudio.TestTools.Utility.AssemblyLoadWorker.GetDependentAssemblies(string path)	Unknown
 	[AppDomain (vstest.executionengine.exe, #1) -> AppDomain (Dependency finder domain, #4)]

**Comment by tillig** [comment]
For better or worse, .NET assembly versioning works this way - not just Autofac, but pretty much every package out there. It's been this way since .NET 1.0 strong naming and since NuGet came in the scene. You don't need to control the .exe to manually add a .exe.config file with binding redirects in the same folder. In any case, no repro means I can't help any more than I have.

**Comment by bencyoung** [comment]
That's a shame as it means we can't really switch to Autofac.

 Note there are quite a few resources out there saying how to use strong name versions like https://codingforsmarties.wordpress.com/2016/01/21/how-to-version-assemblies-destined-for-nuget/ and https://codeblog.jonskeet.uk/2016/03/28/versioning-conundrum-for-noda-time-help-requested/ which disagree that it has to be done the Autofac way

I can't add a repro that can't be solved by just adding a redirect, but as I say I can't just add a redirect (there are hundreds if not thousands of downsteam exes depending on our utility libraries, that we don't control)

There is a quick fix which is to release a bumped package with a new reference, but I guess that may be tricky for you

Roll on .NET Core and dropped strong names...

**Comment by wildshane** [comment]
This is really strange. So I made a sample project to replicate the issue.
Using AF 3.3.1 and MEF 3.0.3 solution worked fine. Then committed source at this stage.
Upgraded to AF 3.5.2 and immediately got the same exception (as soon as the MEF extension method was called). Then Upgraded MEF to 4.0.0 and same exception still occurring.
But...
Reset back to the previous commit, ran fine. Then upgraded AF to 3.5.2 again. And this time it worked?
And now I cannot possibly get my sample code to a stage where it was failing again.... Thanks, Murphy.
